flags:
  pandoc:
    trypandoc: false
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
- /Users/tov/school/eecs214/dev/skylighting
extra-deps:
- hslua-0.5.0
- texmath-0.9.4.1
resolver: lts-8.16
